### ISSUE TITLE
Write draft/specification for OBJ import

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#148] opened 2015-12-18 08:23 UTC
Try to get an idea how the importer should work internally. Then we can write some code.

**Comment by damccull** [comment] 2016-05-18 05:07
Does this issue indicate there's no way to import an X-Plane created obj file yet?

**Comment by der-On** [comment] 2016-05-24 17:49
Yes. Exactly. Import is not possible yet and not that high on the list.

**Comment by MoToCroSs986** [comment] 2017-12-30 22:19
I would like to see an import button for the aircraft.obj file that Plane Maker 11 creates.  Would make it so much easier to create better and more aircraft.

**Comment by tngreene** [comment] 2018-01-01 17:09
# Lets Talk About OBJ Importers (again)
I'm surprised I haven't closed this bug already.

By now an importer is basically never going to be a part of XPlane2Blender. **The amount of time it would require to make an importer as polished as the exporter could mount on years and would always be playing catch up to all existing exporters in development** (not a fun game to play! The exporter is already always playing catch up to X-Plane!) There are a few projects started on the forums you can checkout if you'd like, however!

# Why Is This Such A Hard Problem?
It is simple to read the vertex table, attributes, animation keyframe table, and turn that into Blender data, some projects can already do this, in fact. The trouble is making **usable projects** again (Blend files that are easy to work with and reditly produce good correct results.) 

## OBJs Don't Save Everything You Want And Need As An Artist
Some of the things things you could never import from an OBJ
- Window Settings
- Text Blocks with scripts, notes, or annotations
- Any non-XPlane2Blender Blender settings we don't care about
- Object, layer, material, and texture names
- A bunch of settings that can't easily be inferred (more on that later)
- Blender's parent child relationships

If the OBJ was produced with comments and correct indentation, you **might** be able to get some of these things back (likely just a few names.) A large complex Blend file without this stuff is a nightmare of an unorganized mess and would make the rest of the manual reverse engineering process even harder.

## Multiple .blend files Can Produce The Same OBJ Content

If A.blend, B.blend, and C.blend can produce the same OBJ, which one should the OBJ be reversed engineered back into? The relationship between XPlane2Blender settings and what appears in the OBJ can be very esoteric and there is not always a 1:1 relationship. Some ATTR_s only appear when certain combinations of settings are used. You may find there are absolutely no good defaults.

## An Importer Would Need To Know Massive Amounts of History Of All Exporters

In order to solve these ambiguities and produce .blend files that are similar to what originally exporter the OBJ file, it would be incredibly useful to know about the behavior of the exporter that exported the OBJ in question. This means an importer would need to know all the bugs and features of every exporter, and we don't even know that after developing the exporter. Bugs are waiting to be discovered, or used by artists until they have to be turned into a feature.

This turns into it's own ambiguities to solve: "Is this OBJ's mention of deprecated ATTR_s a choice the artist made. despite the deprecation warning, or was it a bug that this was still getting written, or was this OBJ written before it was deprecated?" Now you're messing not only with valid or not, but what the OBJ is supposed to look like.

## Optimizations Create Further Challenges

Exporters often take optimizations to improve an OBJ's performance and correctness. For instance:
- Removing duplicated vertices, keyframes, attributes
- Rounding or changing data on the fly
- Ignoring or appending ATTRs to handle deprecations or obsolete OBJ features

Now you will have even less information or, now, seemingly incorrect information! OBJs are meant for X-Plane, not humans. As such exporters can take many liberties with the content of OBJs as long as they match what the artist meant. **This can result in very complex optimizations that might even break our own guidelines, all to deliver the best (and deliver on time) to the consumer and our artists.** This makes developing an importer that reproduces the importer OBJ, either exactly or simply visually matching (let alone animated or textured properly) even harder.

In a raw .blend file, objects are like Lego bricks which get baked into one solid piece. Going in reverse will likely not get the same neat separation. Blender is not smart enough to tell what is a wing shape, what is a wheel shape, what is a throttle level shape. **It may be impossible to separate the vertices back into these distinct meshes (especially after optimizations)! Making a "smart" importer that is shape aware is a brutally hard algorithm that the world's best computer scientists are still attempting to solve.** It may not be challenge you want to take on.

## "Good Enough" Isn't Good Enough For Laminar Research

Yes, you can produce scripts that take OBJs and turn them into .blend files, but of what quality? Any importer, even a "smart" importer that makes reasonable assumptions, would still require hours of error prone manual fixes, especially for broken geometry, every time you import an OBJ. **The complexity of a "smart" importer quickly goes through the roof, and so do the sacrifices. It is always a losing game of catch up with X-Plane.**

If our goal is a **quality and completely useful** experience to our artists, making something that doesn't scale to real projects doesn't make sense to us. Hence why, among other interesting reasons, an importer will not be in XPlane2Blender, especially as more and more versions of exporters are made and the OBJ spec gets more additions, clarifications, and depredations in it.

I hope this is a more meaningful answer than "its just not going to happen, even if it is very often requested."

-Ted

## Post Script About Copyright
If other people want to take on the challenge of making dumb or smart importers and people want to use them despite their obvious draw backs, Laminar Research can't stop them. The spec is open to the public and OBJs are in plain unencrypted text. Whether reverse engineering tools are a good idea for the community is another nuanced question.

For pros (among others):
- Allows people to learn from others
- Allows people to use the generated aircraft,obj as an easy starting point
- Allows people to port their work from any exporter to Blender
- Allows people to recover lost work or dead projects

For cons (among others):
- **Payware artists and others can have their work much more easily copied (which is already a problem)**

This is a particularly disastrous possibility, a sufficiently smart and easy to use importer could add a lot of fuel to the fire.

I don't know what Laminar Research's official stand point is on the matter. As such I'm neutral on the subject. If people have questions about the exporter, I'll answer them. If people want help (during paid hours of off the clock) making an importer I'll have to decline. Most of all I want to see this community thrive and help people as much as possible!

It's a hard position to be in. To address the "learn from others" and "easy starting point" aspects, I'd rather see people making and sharing a collection of template .blend files and projects to learn from that follow current best practice instead of whatever an importer could spit out (good or bad). This is a large undertaking in and of itself of course and must be kept up to date.

### 2.49 to 2.7x Converter
A 2.49 converter may or may not be the works (far far far back on the back burner) without ethical questions because it still requires the original .blend file from 2.49, something only the original IP holder is likely to have (and keep secret.) The complexity of this tool is much more manageable, because 2.49 will never change or have features added to and you are dealing with .blend to .blend, not .obj to .blend, which Blender is already very good at.

**Closed by tngreene** 2018-01-01 17:09 UTC

**Comment by MoToCroSs986** [comment] 2018-01-01 17:44
Ok cool, now I know.  Thanks for all the info.
Won’t waste anymore time.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
