### ISSUE TITLE
Removal of "Loc", "Rot", "LocRot", etc. causes backward compatibility issues.

### ISSUE THREAD

**Issue by danklaue** [der-On/XPlane2Blender#292] opened 2017-08-12 21:32 UTC
This has happened before when Ondrej changed these drop-down menus to the way they've been since v3.20: I had to re-do a BUNCH of animations (and HUNT THEM DOWN in most cases, because it's not obvious which parts of older planes are assigned these show/hide directives), and this is happening again now!

When I export existing projects with the latest (yesterday's) 3.4 release, all "Show" and "Hide" directives are reset to "Transformation", which destroys their "Show/Hide" logic. In a cockpit with hundreds of these instances, this is catastrophic.  

These drop-down menus should be treated with EXTREME CARE, and not flippantly changed to whatever new-fangled functionality is envisioned for them. 

I can't use v3.4 at all, until this is fixed.  

And the tragedy is, every file that I've opened and just SAVED, using this 3.4 commit, has destroyed these Blend files for me. I've got to go and dig up the backups.

**Comment by bsupnik** [comment] 2017-08-12 21:39
Hi Ted,

Please look at this ASAP!  Clearly the expected behavior was that changing the menu would result only in "unused" loc/rot data being dumped and NOT critical show-hide data.  Ping Dan as needed if you need a specific test file to see this problem.

One random thought: if the path from 3.3 -> 3.4 depends on upgrading the data model based on an "old" .blend file, it's possible that this is partly related to Dan using intermediate builds of the exporter.  Something to look at if this looks weirdly unreproducible.

**Comment by tngreene** [comment] 2017-08-13 17:15
Hi @danklaue. I'm so sorry that this has happened. Fortunately a fix already exists in #288. Download that version and try it out. What happened here, probably, is the version got changed, to later when the properties got changed and the updater was supposed to run and fix it, it didn't.

I'm not really sure how this is possible. On that bug number, can you also write the history of those files, which versions of Blender and XPlane2Blender they were created in, edited in, saved in, upgraded in, etc?

**Comment by tngreene** [comment] 2017-08-13 17:15
I'm extremely glad you have backups.

**Comment by tngreene** [comment] 2017-08-13 17:30
Having the backup file and file that got ruined would be extremely helpful if you'd like to e-mail me them or put them here. This is my highest priority bug or anything until this gets fixed.

**Comment by danklaue** [comment] 2017-08-13 23:03
You need .obj files? Or .blend files?

**Comment by tngreene** [comment] 2017-08-14 14:50
Okay! Bug of how we got here:

The loc/rot/locrot transform update was supposed to be a 3.4.0 feature, however it was committed before the the version in __init__.py was changed to ``(3,4,0)``. I was so caught up in thinking about the release of the beta I forgot that there are some people who check stuff out directly from git.

So, there was a brief amount of time where people used an experimental feature without being warned (aside from the fact they were checking stuff out directly from git from neither the known to be very stable v3-3 branch or master branch) that this stuff was very experimental.

The commits in question are
1. fda38adfeed - version changed to 3.3.9 to understand how github uses tags, and to test the updater
2. e8b4173346755 - Adds experimental feature of auto-upgrades
3. 24a97fb1c866cda2 - Adds upgrading bone's anim_type because I forgot to include those. This made this feature complete
4. a091a535252b - version changed to 3.4.0 in __init__.py, v3.4.0b1 released
e8b417334675564

So that's the timeline.

**Comment by tngreene** [comment] 2017-08-14 19:03
Part 2: What happened

So, here is how the updater works

```
pre_34_anim_types | post_34_anim_types
1 [LocRot]        | 1 [ Transform]
2 [Loc]           | (Merged)
3 [Rot]           | (Merged)
4 [Show]          | 2 [Show]
5 [Hide]          | 3 [Hide]
```

The "algorithm" if the pre_34_anim_type is less than the 4th slot, set it to the 1st slot of post_34_anim_types. Otherwise subtract 2 slots.

This is great unless you get updated twice (which you will over time!), in which case every animation type will get subtract slots and be set to "Transform".

The solution? Get a better updater algorithm!

**Comment by tngreene** [comment] 2017-08-15 15:26
This fix is now included in beta2

**Closed by tngreene** 2017-08-15 15:26 UTC
Labels: Bug, priority high
