### ISSUE TITLE
Cleanup UI

### ISSUE THREAD

**Issue by der-On** [der-On/XPlane2Blender#145] opened 2015-12-08 23:57 UTC
Make UI more readable and organized. Currently it's becoming a mess due to the amount of settings.
- [ ] Group things into collapsible boxes
- [ ] Seperate attributes that are only available in certain export types into collapsible groups
- [ ] bring things into usefull order: most used first, least used last

**Comment by tngreene** [comment] 2017-07-19 15:23
Duplicate of #267

**Closed** 2018-01-02 18:05 UTC
Labels: priority normal, ready
