### ISSUE TITLE
Impossible to export object with texture Xpane2blender v3.3.12 in Blender V2.78

### ISSUE THREAD

**Issue by Claudius69** [der-On/XPlane2Blender#249] opened 2017-05-20 17:58 UTC
After I read all the information I found , I can't export object with texture. Objects are well modelised but always appears grey. Objects have materials and texture indicated in Xplane layer and are unwrapped with an image texture in UV Image editor. The only documentation I found is about a previous version of Xpane2blender v3.3.12. Is there somewhere a detailled documentation or tutorial to help me.
Thanks a lot. 
Sorry, il me english is not perfect, I'm french.

**Comment by tngreene** [comment] 2017-05-30 14:59
Can you paste in the first part of the .OBJ file? It will look something like this:

```
I
800
OBJ

TEXTURE	texture.png
```

and may include the word ``POINT_COUNT``

Do you have auto detect textures turned on or off? It is a checkbox on the XPlane Layer

**Comment by Colimata** [comment] 2017-07-04 11:49
There seems to be an additional hurdle now (3.3.14) when exporting with textures. 
Apparently the texture applied to the material must be the same as the one in the export layer definition (scene tab). While this could be handy sometimes I'm not sure if this rigid "lock" is ideal.
1.) Beginners could not be able to export anything (not even a gray OBJ that could be hacked - need to activate the Debug mode with log file and investigate)
2.) On bigger projects, one needs to reuse materials (and textures) in different layers to assure uniformity in the project. But now every layer seems to need a separate material set.

Probably there is a deeper idea behind this, however.
Thanks meanwhile.
Florian
COLIMATA

**Comment by tngreene** [comment] 2017-07-18 14:45
Are you using the Autodetect Textures feature? Usually that is enough for most people and they will not have to resort manually entering texture paths.

**Comment by tngreene** [comment] 2017-07-18 16:48
Possibly a duplicate of #213

**Comment by Colimata** [comment] 2017-07-19 08:40
Problem solved on version 3.3.13(v3-3 branch) - blender 2.78!
Could be the same for #213.
Thank you guys for your work on this!

**Comment by tngreene** [comment] 2017-07-19 15:08
Thanks for the update. Closed!

**Closed by tngreene** 2017-07-19 15:08 UTC
